projectName: >-
  Submit product listing to following directory pages and show step-by-step
  instructions: 

  Product Hunt

  TechCrunch

  HackerNews 

  Crunchbase 

  Betalist

  All top startups

  Mashable

  Stripe

  Forbes Technology

  Growth Hackers 

  Peerlist

  YourStory

  Hashnode

  Wellfound

  Capterra

  Beta Bound

  Android Authority

  Foundr

  Biggerpockets.com

  CrozDesk

  Entrepreneur

  Geekwire

  AlternativeTo

  Behance

  BostInno Startups, Tech News and Events

  Digg

  FinancesOnline.com

  Launching Next

  Healthline

  Alternative.me

  Android United

  Appiod.com

  AppsThunder

  Changelog

  Creative Tribes

  DEV Community

  FeedMyStartup

  Front-End Developers

  GeekWire

  Atlassian

  Microsoft Dev Chat

  Netted

  New Startups

  SaaS Directory

  SaaSHub

  SaaSworthy

  Silicon Prairie Tech

  Mind the product

  Slant

  SoftwareSuggest

  Startupbeat

  Startup Buffer

  Startup Collections

  Startup Europe

  Inspiration gallery for startups

  Startup Roulette

  Startuptabs

  Tech directory

  Techendo

  Submit A Startup

  Robin Good's Tools

  Trustpilot

  TrustRadius

  Venture Village

  Webrazzi

  Web Tools Weekly 

  Women in Technology

  AppsMirror

  Engadget

  Fastcompany

  Gizmodo

  Huffingtonpost

  KillerStartup

  Mac Stories

  MakeUseOf

  Similar Sites

  Superb Crew

  TechPluto

  Guardian Technology

  The Register UK

  Top Similar Sites

  Wired

  1000 Tools

  10Words

  All my faves

  All Top

  AllTopStartups

  AlphaDigits

  Angellist

  Apprater

  AwesomeIndie

  Betabound

  PitchWall

  Real World Beta Testing

  Broadwise.org

  Clutch

  CoFoundersLab

  Growth hackers

  CtrlAltCC

  DevDojo

  Devpost

  devRant

  Dribbble

  e27

  Elpha

  Softonic

  Finances Online

  Firebase

  FreeCodeCamp

  Future Startup

  Worm

  HackerNoon

  Hackers Pad

  Mashable India

  Inc42

  iOS Developers

  Land Book

  Launched!

  Lobsters

  NextBigWhat

  One Thing Well

  Online Geniuses

  Open Startup List

  Owwly

  Promotehour

  Read.cv

  Resource FYI

  AppSumo

  G2

  SiliconANGLE

  Babel Slack

  Cloud Foundry

  Cloud Native Computing Foundation

  Slate

  The Best Startup Newsletters for Founders AND Investors

  SourceForge

  Starticorn

  Startup88

  Startupbase

  StartUp Beat

  Snap Munk

  Startup Stash

  Startup Tile

  Startup Tracker

  Tech.co

  EU Tech

  Techboard

  Techli

  Tech Pluto

  Hive Index

  Startup Pitch

  Thingtesting

  Tidy Repo

  Tech | Time

  RobinGood

  ToolSalad 

  Towards Data Science

  Tracxn

  UX Design Weekly

  Vator

  Venture Beat

  Webthat

  Web Tools Weekly

  We Work Remotely

  WP Newsify

  9Sites.net 

  Addictive Tips

  Admire The Web

  AffordHunt

  Android Central

  Android Headlines

  Buffer apps

  Built in Chicago

  Business Insider India

  Capterra - For Vendors

  Classical Finance

  CNET

  CodeProject

  Crazy About Startups

  Data Quest

  EU-Startups Database

  F6S

  Fast Company

  Featured Customers

  Feedough

  Fuse.kiwi

  GetApp

  Getting Smart

  All Software Categories - GoodFirms

  GrowthBoosters

  HuffPost

  Inc. Magazine

  Indiehacker tools

  Indiehackers

  InfoWorld

  Insanely cool tools

  Joinly

  KillerStartup

  Landing Folio

  Make Use of

  MarketingProfs

  Microstartups

  Nocode Devs

  PCMag

  PC World

  Product HQ

  Psychology Today

  r/advancedentrepreneur/

  r/ArtificialInteligence/

  r/design_critiques/

  r/EntrepreneurRideAlong/

  r/GrowthHacking/

  r/IMadeThis/

  r/indiebiz/

  r/indiehackers/

  r/InternetIsBeautiful/

  r/ladybusiness/

  r/microsaas/

  r/NicheWebsites/

  r/betatests

  r/nocode/

  r/ProductHunters/

  r/roastmystartup/

  r/SaaS/

  /r/Plugyourproduct/

  r/sideproject

  r/Startup_Ideas/

  r/startups/

  Remote Tools

  SaaS Genius

  saashub.com/

  SaaS Worthy

  SideProjectors

  SitePoint Forums 

  Smashing Magazine

  Software Suggest

  SoftwareWorld

  Starter Story

  StartupBlink

  Startup inspiration

  The Startup Project

  Startup Ranking

  Startups List

  Startups FYI

  Tech in Asia

  MIT Technology Review

  TechRepublic

  Startup Digest: More Than Just a Newsletter | Techstars

  The Startup INC

  The Verge

  Uneed

  Unita 

  Website Hunt

  The Wall Street Journal

  Quora

  r/design

  r/entrepreneurship

  r/frontend

  r/programming

  r/saas

  r/technology

  r/userexperience

  r/webdesign

  /r/thesidehustle/

  r/Advertising

  r/AskMarketing

  r/Business_Ideas

  r/Businessideas

  r/coupons

  r/eCommerce

  r/EmailMarketing

  r/GrowthHacking

  r/Marketing

  r/NoCodeSaaS/

  r/Plugyourproduct

  r/Retail

  r/Sales

  r/startup_resources

  r/startup

  r/streetwearstartup

  r/VentureCapital

  r/VenturedCapital

  r/WebMarketing

  SaaS Hub

  Online Geniuses 

  TechLondon

  Growmance 

  Indie London

  People Ops & HR Community 

  Landscape

  Product School

  #TechMasters

  Startup Resources

  Snowball club

  eCommerceFuel

  Startup Grind

  Product-Led Alliance

  No Code Founders

  Fastlane Forum

  WeAreNoCode

  buildspace

  Kernal

  founderio

  FoundersList

  r/SweatyStartup

  Startup Resources

  r/Socialpreneur

  r/AlphaandBetausers

  r/growinpublic

  r/testmyapp

  r/GrowMyBusiness

  r/DotCom

  Furlough

  Tech Startup Community 

  Makers HQ

  Founderopedia 

  Startup Chat

  Entrepreneur's network

  Band of Entrepreneurs 

  Startup Specialists Group

  Executive Suite 

  GenZ VCs 

  Stripe Discord Server 

  OpenAI discord Server 

  Retool Discord Server 

  SEOUL Startups

  Remotely One 

  Belkins B2B Sales 

  Outreach Desk

  Loqol Startup Community

  Makers Community 

  Startup India 

  Makerspace

  On Startups

  Dev Hunt

  Dang.ai

  Venture Radar

  SaaSBaba

  aitools.fyi

  Easy With AI

  SaaS AI Tools

  TEXTIFY

  AI Tools Directory

  ToolPilot AI

  AI Stash

  aiwizard

  GPTE

  AI Finder

  300+ Best AI Tools 

  Ben Bites News

  Igniter AI

  Futurepedia

  Discover the best artificial intelligence tools

  Future AGI Tools

  AI Depot

  AI Startups

  Mad Genius

  The AI Warehouse

  Ai Tool Hunt

  AI ToolBoard

  AI Marketing Directory

  NextPedia

  Tool Scout

  The Ultimate ChatGPT Database

  AI Tools Directory

  AI Tool Details

  AI Awesome

  TopAI.tools

  Toolify

  Supertools

  AI Scout

  Postmake

  Romanian Startups

  Serchen

  List Your Software & Get Qualified Leads

  Startups.watch

  Web3Canvas

  Tech Tools Directory

  Vccircle

  Unboxing Startups

  unita 

  There's An AI For That

  MicroLaunch

  Google Business Profile

  Startupxplore

  Pocket-lint

  BuzzFeed News

  Sitejabber

  SaasGenius
jsonFilePath: ./input.json
baseUrl: https://productlaunchlist.com
portalHeading: Launch Faster
portalDescription: Launch your product across 100+ directories in just one click.
portalTitle: Product Launch List
searchPlaceholder: Search for products...
useAlphabetsCategory: true
homeLink: https://productlaunchlist.com/
logoLink: https://productlaunchlist.com/
ctaText: Get Started
aboutLink: https://productlaunchlist.com/about
productsLink: https://productlaunchlist.com/products
logoImgUrl: https://productlaunchlist.com/logo.png
ctaLink: https://productlaunchlist.com/get-started
copyrightText: © 2023 Product Launch List. All rights reserved.
faviconUrl: https://productlaunchlist.com/favicon.ico
googleTagManagerId: ''
pagesTitle:
  prefix: ''
  suffix: ''
categoryPagesTitle:
  prefix: ''
  suffix: ''
templateRoot:
  - ./templates
  - ./templates
homeTemplatePath: ./templates/homePageTemplate.ejs
categoryTemplatePath: ./templates/categoryTemplate.ejs
pageTemplatePath: ./templates/pagesTemplate.ejs
outputDir: ./output
socialLinks:
  - platform: Twitter
    url: https://twitter.com/productlaunchlist
  - platform: Facebook
    url: https://facebook.com/productlaunchlist
theme:
  primaryColor: '#007bff'
  secondaryColor: '#6c757d'
  backgroundColor: '#ffffff'
  textColor: '#212529'
  accentColor: '#ffc107'
fonts:
  - family: Arial
    weights:
      - 400
      - 500
      - 600
  - family: Verdana
    weights:
      - 500
      - 600
      - 700
